# Generated by Django 5.2.6 on 2026-02-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='スラッグ')),
                ('content', models.TextField(verbose_name='本文（Markdown）')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='抜粋')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='サムネイル')),
                ('category', models.CharField(choices=[('claude_basics', 'Claude 基本'), ('claude_code', 'Claude Code'), ('claude_config', 'Claude 設定'), ('claude_skills', 'Claude Skills')], max_length=50, verbose_name='カテゴリ')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'ordering': ['-published_at'],
            },
        ),
    ]
