# Generated by Django 5.2.6 on 2026-02-17 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='スラッグ')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.classification', verbose_name='親分類')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.classification', verbose_name='分類'),
        ),
    ]
