# Generated by Django 5.2.6 on 2026-02-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_category_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='短縮タイトル（サイドバー用）'),
        ),
    ]
