# Generated by Django 5.2.6 on 2026-02-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_short_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True, verbose_name='用語')),
                ('reading', models.CharField(blank=True, max_length=100, verbose_name='読み')),
                ('description', models.TextField(verbose_name='説明')),
            ],
            options={
                'verbose_name': '用語',
                'verbose_name_plural': '用語',
                'ordering': ['term'],
            },
        ),
    ]
