# Generated by Django 5.2.6 on 2026-03-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_glossaryterm_alter_article_content_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='本文（HTML）'),
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='サービス名')),
                ('url', models.URLField(max_length=500, verbose_name='アフィリエイトURL')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='説明文')),
                ('display_text', models.CharField(default='詳しく見る', max_length=100, verbose_name='表示テキスト')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('classifications', models.ManyToManyField(blank=True, related_name='affiliate_links', to='blog.classification', verbose_name='対象分類')),
            ],
            options={
                'verbose_name': 'アフィリエイトリンク',
                'verbose_name_plural': 'アフィリエイトリンク',
                'ordering': ['order', 'service_name'],
            },
        ),
    ]
