# Generated by Django 5.2.6 on 2026-03-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_content_affiliatelink_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['order', '-published_at'], 'verbose_name': '記事', 'verbose_name_plural': '記事'},
        ),
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
    ]
