# Generated by Django 5.2.6 on 2026-03-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_add_article_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='badge',
            field=models.CharField(blank=True, help_text='例: おすすめ, 人気No.1', max_length=30, verbose_name='バッジテキスト'),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='color',
            field=models.CharField(default='#10b981', help_text='例: #10b981', max_length=7, verbose_name='テーマカラー'),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='icon',
            field=models.CharField(blank=True, help_text='例: bi-hdd-rack, bi-globe, bi-server', max_length=50, verbose_name='アイコン（Bootstrap Icons）'),
        ),
    ]
