# Generated by Django 5.2.6 on 2026-03-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_affiliatelink_badge_affiliatelink_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_tweeted',
            field=models.BooleanField(default=False, verbose_name='X投稿済み'),
        ),
    ]
