# Generated by Django 5.2.6 on 2026-03-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_add_is_tweeted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossaryterm',
            name='reading',
        ),
    ]
