# Generated by Django 5.2.6 on 2026-04-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_glossaryterm_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='book_title',
            field=models.CharField(blank=True, help_text='書籍の場合に設定。書籍カードとして表示される', max_length=200, verbose_name='書籍タイトル'),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='image_url',
            field=models.URLField(blank=True, help_text='書影画像のURL', max_length=500, verbose_name='画像URL'),
        ),
    ]
