# Generated by Django 5.2.6 on 2026-02-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='取得日時')),
                ('tickers_count', models.IntegerField(default=0, verbose_name='取得銘柄数')),
                ('success', models.BooleanField(default=True, verbose_name='成功')),
                ('message', models.TextField(blank=True, verbose_name='メッセージ')),
            ],
            options={
                'verbose_name': '取得ログ',
                'verbose_name_plural': '取得ログ',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, verbose_name='ティッカー')),
                ('name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='時刻')),
                ('open', models.FloatField(verbose_name='始値')),
                ('high', models.FloatField(verbose_name='高値')),
                ('low', models.FloatField(verbose_name='安値')),
                ('close', models.FloatField(verbose_name='終値')),
                ('volume', models.BigIntegerField(default=0, verbose_name='出来高')),
            ],
            options={
                'verbose_name': '株価データ',
                'verbose_name_plural': '株価データ',
                'ordering': ['ticker', 'timestamp'],
                'indexes': [models.Index(fields=['ticker', 'timestamp'], name='stock_monit_ticker_8501a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticker', 'timestamp'), name='unique_ticker_timestamp')],
            },
        ),
    ]
