# Generated by Django 5.2.6 on 2026-02-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, verbose_name='ティッカー')),
                ('name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('date', models.DateField(db_index=True, verbose_name='日付')),
                ('open', models.FloatField(verbose_name='始値')),
                ('high', models.FloatField(verbose_name='高値')),
                ('low', models.FloatField(verbose_name='安値')),
                ('close', models.FloatField(verbose_name='終値')),
                ('volume', models.BigIntegerField(default=0, verbose_name='出来高')),
            ],
            options={
                'verbose_name': '日足データ',
                'verbose_name_plural': '日足データ',
                'ordering': ['ticker', 'date'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='stock_monit_ticker_64557e_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticker', 'date'), name='unique_ticker_date')],
            },
        ),
    ]
