# Generated by Django 5.2.6 on 2026-02-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_monitor', '0002_dailystockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFundamentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, verbose_name='ティッカー')),
                ('date', models.DateField(db_index=True, verbose_name='日付')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='時価総額')),
                ('per', models.FloatField(blank=True, null=True, verbose_name='PER')),
                ('pbr', models.FloatField(blank=True, null=True, verbose_name='PBR')),
                ('dividend_yield', models.FloatField(blank=True, null=True, verbose_name='配当利回り(%)')),
                ('eps', models.FloatField(blank=True, null=True, verbose_name='EPS')),
                ('roe', models.FloatField(blank=True, null=True, verbose_name='ROE(%)')),
                ('revenue', models.BigIntegerField(blank=True, null=True, verbose_name='売上高')),
                ('profit_margin', models.FloatField(blank=True, null=True, verbose_name='利益率(%)')),
                ('fifty_two_week_high', models.FloatField(blank=True, null=True, verbose_name='52週高値')),
                ('fifty_two_week_low', models.FloatField(blank=True, null=True, verbose_name='52週安値')),
            ],
            options={
                'verbose_name': 'ファンダメンタルズ',
                'verbose_name_plural': 'ファンダメンタルズ',
                'ordering': ['ticker', '-date'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='stock_monit_ticker_5e92be_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticker', 'date'), name='unique_fundamentals_ticker_date')],
            },
        ),
    ]
