# Generated by Django 5.2.6 on 2026-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_monitor', '0003_stockfundamentals'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(db_index=True, verbose_name='イベント日')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='イベント時刻')),
                ('country', models.CharField(max_length=5, verbose_name='国コード')),
                ('event_name', models.CharField(max_length=200, verbose_name='イベント名')),
                ('actual', models.CharField(blank=True, max_length=50, verbose_name='実績値')),
                ('forecast', models.CharField(blank=True, max_length=50, verbose_name='予想値')),
                ('previous', models.CharField(blank=True, max_length=50, verbose_name='前回値')),
                ('impact', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='重要度')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='単位')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='取得日時')),
            ],
            options={
                'verbose_name': '経済イベント',
                'verbose_name_plural': '経済イベント',
                'ordering': ['event_date', 'event_time'],
                'indexes': [models.Index(fields=['event_date', 'country'], name='stock_monit_event_d_1ff8e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_date', 'country', 'event_name'), name='unique_economic_event')],
            },
        ),
        migrations.CreateModel(
            name='FinancialNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finnhub_id', models.BigIntegerField(unique=True, verbose_name='Finnhub ID')),
                ('title', models.CharField(max_length=500, verbose_name='タイトル')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('source', models.CharField(max_length=100, verbose_name='ソース')),
                ('summary', models.TextField(blank=True, verbose_name='要約')),
                ('category', models.CharField(choices=[('general', '全般'), ('forex', '為替'), ('crypto', '仮想通貨'), ('merger', 'M&A')], default='general', max_length=20, verbose_name='カテゴリ')),
                ('related_tickers', models.CharField(blank=True, max_length=500, verbose_name='関連ティッカー')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='画像URL')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='公開日時')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='取得日時')),
            ],
            options={
                'verbose_name': '金融ニュース',
                'verbose_name_plural': '金融ニュース',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='stock_monit_publish_53a3ed_idx'), models.Index(fields=['category', '-published_at'], name='stock_monit_categor_c31ef3_idx')],
            },
        ),
    ]
