# Generated by Django 5.2.6 on 2026-02-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_monitor', '0004_economicevent_financialnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EconomicEvent',
        ),
        migrations.DeleteModel(
            name='FinancialNews',
        ),
    ]
