from django.urls import path

from . import views

app_name = "tools"

urlpatterns = [
    path("", views.index, name="index"),
    path("ip-lookup/", views.ip_lookup, name="ip_lookup"),
    path("json-formatter/", views.json_formatter, name="json_formatter"),
    path("base64/", views.base64_tool, name="base64"),
    path("password-generator/", views.password_generator, name="password_generator"),
    path("qr-code/", views.qr_code, name="qr_code"),
    path("char-counter/", views.char_counter, name="char_counter"),
    path("whois/", views.whois_lookup, name="whois"),
    path("regex-tester/", views.regex_tester, name="regex_tester"),
    path("cron-generator/", views.cron_generator, name="cron_generator"),
    path("color-converter/", views.color_converter, name="color_converter"),
    path("url-encode/", views.url_encode, name="url_encode"),
    path("unix-time/", views.unix_time, name="unix_time"),
    path("diff/", views.diff_tool, name="diff"),
    path("hash-generator/", views.hash_generator, name="hash_generator"),
    path("html-escape/", views.html_escape, name="html_escape"),
    path("jwt-decoder/", views.jwt_decoder, name="jwt_decoder"),
    path("unit-converter/", views.unit_converter, name="unit_converter"),
    path("age-calculator/", views.age_calculator, name="age_calculator"),
    path("http-headers/", views.http_headers, name="http_headers"),
    path("ssl-checker/", views.ssl_checker, name="ssl_checker"),
    path("port-scanner/", views.port_scanner, name="port_scanner"),
    path("password-strength/", views.password_strength, name="password_strength"),
    path("subnet-calculator/", views.subnet_calculator, name="subnet_calculator"),
    path("speech-to-text/", views.speech_to_text, name="speech_to_text"),
    path("network-sim/", views.network_sim, name="network_sim"),
    path("markdown-preview/", views.markdown_preview, name="markdown_preview"),
    path("image-compress/", views.image_compress, name="image_compress"),
    path("sql-formatter/", views.sql_formatter, name="sql_formatter"),
    path("csv-json/", views.csv_json, name="csv_json"),
    path("compound-interest/", views.compound_interest, name="compound_interest"),
    path("loan-calculator/", views.loan_calculator, name="loan_calculator"),
    path("currency-converter/", views.currency_converter, name="currency_converter"),
    path("text-transform/", views.text_transform, name="text_transform"),
    path("dummy-text/", views.dummy_text, name="dummy_text"),
    path("typing-test/", views.typing_test, name="typing_test"),
    path("pdf-tool/", views.pdf_tool, name="pdf_tool"),
    path("text-proofreader/", views.text_proofreader, name="text_proofreader"),
    path("ruby-generator/", views.ruby_generator, name="ruby_generator"),
    path("image-converter/", views.image_converter, name="image_converter"),
    path("ogp-preview/", views.ogp_preview, name="ogp_preview"),
    path("favicon-generator/", views.favicon_generator, name="favicon_generator"),
    path("yaml-json/", views.yaml_json, name="yaml_json"),
    path("env-json/", views.env_json, name="env_json"),
    path("http-status/", views.http_status, name="http_status"),
    path("ogp-generator/", views.ogp_generator, name="ogp_generator"),
    path("split-bill/", views.split_bill, name="split_bill"),
    path("bmi-calculator/", views.bmi_calculator, name="bmi_calculator"),
    path("date-calculator/", views.date_calculator, name="date_calculator"),
    path("email-header/", views.email_header, name="email_header"),
    # 情報収集
    path("weather/", views.weather, name="weather"),
    path("zip-code/", views.zip_code, name="zip_code"),
    path("holidays/", views.holidays, name="holidays"),
    path("wikipedia/", views.wikipedia, name="wikipedia"),
    path("trivia-quiz/", views.trivia_quiz, name="trivia_quiz"),
    path("cocktail-recipe/", views.cocktail_recipe, name="cocktail_recipe"),
    path("geocoding/", views.geocoding, name="geocoding"),
    # API
    path("api/ogp-preview/", views.api_ogp_preview, name="api_ogp_preview"),
    path("api/ip-lookup/", views.api_ip_lookup, name="api_ip_lookup"),
    path("api/whois/", views.api_whois, name="api_whois"),
    path("api/http-headers/", views.api_http_headers, name="api_http_headers"),
    path("api/ssl-check/", views.api_ssl_check, name="api_ssl_check"),
    path("api/port-scan/", views.api_port_scan, name="api_port_scan"),
    path("api/weather/", views.api_weather, name="api_weather"),
    path("api/wikipedia/", views.api_wikipedia, name="api_wikipedia"),
    path("api/geocoding/", views.api_geocoding, name="api_geocoding"),
]
