# Generated by Django 5.2.6 on 2026-02-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_key', models.CharField(db_index=True, max_length=20, verbose_name='都市キー')),
                ('city_name', models.CharField(max_length=50, verbose_name='都市名')),
                ('forecast_date', models.DateField(db_index=True, verbose_name='予報日付')),
                ('weather_code', models.IntegerField(verbose_name='天気コード')),
                ('temp_max', models.FloatField(verbose_name='最高気温')),
                ('temp_min', models.FloatField(verbose_name='最低気温')),
                ('precipitation_prob', models.IntegerField(verbose_name='降水確率')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='現在気温')),
                ('humidity', models.IntegerField(blank=True, null=True, verbose_name='現在湿度')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='現在風速')),
                ('current_weather_code', models.IntegerField(blank=True, null=True, verbose_name='現在天気コード')),
                ('fetched_at', models.DateTimeField(verbose_name='取得日時')),
            ],
            options={
                'verbose_name': '天気予報',
                'verbose_name_plural': '天気予報',
                'constraints': [models.UniqueConstraint(fields=('city_key', 'forecast_date'), name='unique_city_forecast_date')],
            },
        ),
    ]
