# Generated by Django 5.2.6 on 2026-03-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('python', 'Python')], db_index=True, max_length=20, verbose_name='言語')),
                ('question_format', models.CharField(choices=[('fill', '穴埋め'), ('choice', '選択'), ('output', '出力予測'), ('error', 'エラー発見')], max_length=20, verbose_name='形式')),
                ('difficulty', models.IntegerField(default=1, help_text='1=初級, 2=中級, 3=上級', verbose_name='難易度')),
                ('question_text', models.TextField(verbose_name='問題文')),
                ('code_snippet', models.TextField(blank=True, verbose_name='コードスニペット')),
                ('choice_1', models.CharField(max_length=500, verbose_name='選択肢1')),
                ('choice_2', models.CharField(max_length=500, verbose_name='選択肢2')),
                ('choice_3', models.CharField(max_length=500, verbose_name='選択肢3')),
                ('choice_4', models.CharField(max_length=500, verbose_name='選択肢4')),
                ('correct_choice', models.IntegerField(help_text='1〜4', verbose_name='正解番号')),
                ('explanation', models.TextField(verbose_name='解説')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'クイズ問題',
                'verbose_name_plural': 'クイズ問題',
            },
        ),
    ]
