# Generated by Django 5.2.6 on 2026-04-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeafloorDepth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_e4', models.IntegerField(verbose_name='緯度×10000')),
                ('lon_e4', models.IntegerField(verbose_name='経度×10000')),
                ('elevation', models.FloatField(blank=True, null=True, verbose_name='標高/水深 (m)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='取得日時')),
            ],
            options={
                'verbose_name': '海底深度キャッシュ',
                'verbose_name_plural': '海底深度キャッシュ',
                'indexes': [models.Index(fields=['lat_e4', 'lon_e4'], name='tools_seafl_lat_e4_6d9f79_idx')],
                'constraints': [models.UniqueConstraint(fields=('lat_e4', 'lon_e4'), name='unique_seafloor_latlon')],
            },
        ),
    ]
